Adding new steps and updating Set New RC Ver step to increment version number based on Semver label

diff --git a/.github/workflows/github-actions-release-candidate.yml b/.github/workflows/github-actions-release-candidate.yml
--- a/.github/workflows/github-actions-release-candidate.yml
+++ b/.github/workflows/github-actions-release-candidate.yml
@@ -15,6 +15,27 @@ jobs:
       GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
       NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
     steps:
+      - name: Check for required Semver labels
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const requiredLabels = ['Major', 'Minor', 'Patch'];
+            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+            });
+            const presentLabels = labels.map(label => label.name);
+            const presentRequiredLabel = requiredLabels.filter(label => presentLabels.includes(label));
+
+            if (presentRequiredLabels.length === 0) {
+              core.setFailed('Your pull request is missing a required Semver label: (${requiredLabels.join(', ')})');
+            else if (presentRequiredLabels.length > 1) {
+              core.setFailed('Your pull request has multiple Semver labels. Please use only one.')
+            } else {
+              console.log('Pull request has a required Semver label.');
+            }
       - uses: actions/checkout@v3
       - name: 'Enable registry auth'
         shell: bash
@@ -30,27 +51,40 @@ jobs:
         with:
           bundler-cache: true
       - name: Python Setup
-        uses: actions/setup-python@v4 
-        with: 
+        uses: actions/setup-python@v4
+        with:
           python-version: '3.9'
       - name: Set Git Config
         run: |
           git config --local user.name "${{ github.actor }}"
           git config --local user.email "${{ github.actor }}@users.noreply.github.com"
+      - name: Determine version increment type
+        id: version-label
+        run: |
+          if [[ ${{ contains(github.event.pull_request.labels.*.name, 'Major') }} == 'true' ]]; then
+            echo "INCREMENT=major" >> $GITHUB_OUTPUT
+          elif [[ ${{ contains(github.event.pull_request.labels.*.name, 'Minor') }} == 'true' ]]; then
+            echo "INCREMENT=minor" >> $GITHUB_OUTPUT
+          elif [[ ${{ contains(github.event.pull_request.labels.*.name, 'Patch') }} == 'true' ]]; then
+            echo "INCREMENT=patch" >> $GITHUB_OUTPUT
+          else
+            echo "No valid version label found. Please add a Major, Minor, or Patch label to the PR."
+            exit 1
+          fi
       - name: Grab Current Version and Set New RC Version
         id: set-version
         run: |
           current_npm_version=$(node -pe "require('./package.json').version")
-          
+
           if [[ $current_npm_version == *"-rc."* ]]; then
             new_npm_version=$(yarn version --prerelease --preid rc --no-git-tag-version | grep "New version:" | awk '{print $4}')
           else
-            new_npm_version=$(yarn version --preminor --preid rc --no-git-tag-version | grep "New version:" | awk '{print $4}')
+            new_npm_version=$(yarn version --${{ steps.version-label.outputs.INCREMENT }} --preid rc --no-git-tag-version | grep "New version:" | awk '{print $4}')
           fi
-          
+
           new_npm_version=${new_npm_version#v}
           new_ruby_version=$(echo $new_npm_version | sed 's/-rc\./.pre.rc./')
-          
+
           echo "new_npm_version=${new_npm_version}" >> $GITHUB_ENV
           echo "new_ruby_version=${new_ruby_version}" >> $GITHUB_ENV
       - name: Check if version exists and increment if necessary
